// Generated by scripts/brand-manifest.mjs — do not edit.
// Regenerated on every build; run `npm run brand:manifest` after changing
// anything in public/brand/.

export const BRAND_MANIFEST: Record<string, string> = {
  "favicon": "/brand/favicon.png",
  "mark-brand": "/brand/mark-brand.png",
  "mark-dark": "/brand/mark-dark.png",
  "mark-light": "/brand/mark-light.png",
  "og": "/brand/og.png",
  "riyal": "/brand/riyal.png",
  "welcome-ar": "/brand/welcome-ar.png",
  "wordmark-brand": "/brand/wordmark-brand.png",
  "wordmark-dark": "/brand/wordmark-dark.png",
  "wordmark-light": "/brand/wordmark-light.png"
};
